app/views/auth.py
from flask import Blueprint, render_template, url_for, redirect, flash, request
from flask_login import current_user, login_user, logout_user, login_required

from app.models import User
from app.forms import LoginForm, RegistrationForm, RequestResetForm, ResetPasswordForm
from app.controllers import (
    generate_password_reset_url,
    send_email,
    accessed_links,
    confirm_token,
)
from app.logger import log

auth_blueprint = Blueprint("auth", __name__)


@auth_blueprint.route("/signup", methods=["GET", "POST"])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))
    form = RegistrationForm(request.form)
    if form.validate_on_submit():
        user = User(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            email=form.email.data,
            country=form.country.data,
            organization=form.organization.data,
        )
        user.set_password(form.password.data)
        user.save()
        # login_user(user)
        flash("Registration successful.", "success")
        log(log.DEBUG, "Registration successful.")

        # SEND CONFIRMATION EMAIL
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            confirm_url = generate_password_reset_url(user.email)
            html = render_template(
                "auth/email_signup_confirmation.html",
                confirm_url=confirm_url,
                first_name=user.first_name,
                last_name=user.last_name,
                email=user.email,
            )
            subject = "Greetings from Visual Approach Analytics!"
            send_email(user.email, subject, html)
            log(
                log.DEBUG,
                "A confirmation email has been sent.",
            )

        return redirect(url_for("auth.signin"))
    elif form.is_submitted():
        for error in form.errors:
            for msg in form.errors[error]:
                log(log.ERROR, "signup(): %s", msg)
                flash(msg, "danger")
    return render_template("auth/register.html", form=form, dashboards=accessed_links())


@auth_blueprint.route("/signin", methods=["GET", "POST"])
def signin():
    if current_user.is_authenticated:
        return redirect(url_for("main.index"))
    form = LoginForm(request.form)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None or not user.check_password(form.password.data):
            flash("Wrong email or password.", "danger")
            log(log.ERROR, "Wrong email or password.")
            return redirect(url_for("auth.signin"))
        user.authenticated = True
        user.save()
        login_user(user)
        # flash("Login successful.", "success")
        log(log.DEBUG, "Login successful.")
        return redirect(url_for("main.index"))
    return render_template("auth/login.html", form=form, dashboards=accessed_links())


@auth_blueprint.route("/logout")
@login_required
def logout():
    user = current_user
    user.authenticated = False
    user.save()
    logout_user()
    log(log.DEBUG, "You were logged out.")
    # flash("You were logged out.", "info")
    return redirect(url_for("main.index"))


@auth_blueprint.route("/reset_password", methods=["GET", "POST"])
def reset_request():
    form = RequestResetForm()
    if form.validate_on_submit():
        logout_user()
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            confirm_url = generate_password_reset_url(user.email)
            html = render_template(
                "auth/email_password_reset_confirmation.html",
                confirm_url=confirm_url,
                first_name=user.first_name,
                last_name=user.last_name,
            )
            subject = "Reset password request"
            send_email(user.email, subject, html)
            flash(
                "An email has been sent with instructions to reset your password.",
                "info",
            )
            log(
                log.DEBUG,
                "An email has been sent with instructions to reset your password.",
            )
    return render_template(
        "auth/reset_password_request.html",
        title="Reset Password",
        form=form,
        dashboards=accessed_links(),
    )


@auth_blueprint.route("/reset_password/<token>", methods=["GET", "POST"])
def reset_password(token):
    email = "unknown"
    try:
        email = confirm_token(token)
    except Exception:
        flash("The confirmation link is invalid or has expired.", "danger")
        log(log.ERROR, "The confirmation link is invalid or has expired.")
    user = User.query.filter_by(email=email).first_or_404()
    if not user:
        flash("That is an invalid or expired token.", "warning")
        log(log.ERROR, "That is an invalid or expired token.")
        return redirect(url_for("auth.signin"))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user.set_password(form.password.data)
        user.save()
        flash("Your password has been changed!", "info")
        log(log.DEBUG, "Your password has been changed!")
        return redirect(url_for("auth.signin"))
    return render_template(
        "auth/reset_token.html", form=form, dashboards=accessed_links()
    )

app/templates/_macros.html
<!-- Put your reusable template code into macros here -->

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>{{ config.APP_NAME }}</title>
    <!-- meta -->
    <meta name="description" content="" />
    <meta name="author" content="" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    {% block meta %}{% endblock %}
    <!-- styles -->
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link
      href="{{ url_for('static', filename='css/main.css') }}"
      rel="stylesheet"
      media="screen"
    />
    {% block links %}{% endblock %}
  </head>

  <body>
    <!-- Header -->
    <header>
      <!-- Navigation -->
      <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <div class="container">
          <!-- Navbar Brand -->
          <a class="navbar-brand" href="{{ url_for('main.index') }}"
            >{{ config.APP_NAME }}</a
          >
          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <!-- Main Navigation -->
            <ul class="navbar-nav">
              <li class="nav-item dropdown">
                <a
                class="nav-link dropdown-toggle"
                href="#"
                id="navbarDropdownMenuLink2"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
                >
                Data Explorer
              </a>
              <div
              class="dropdown-menu"
              aria-labelledby="navbarDropdownMenuLink2"
              >
                {% for dashboard in dashboards%}
                  <a
                    class="dropdown-item"
                    href="{{ dashboard.url }}"
                    >{{ dashboard.title }}</a
                  >
                  {% endfor %}
                </div>
              </li>
            </ul>
            <!-- Login/Logout -->
            <ul class="navbar-nav ml-auto">
              {% if current_user.is_authenticated %}
              <li class="nav-item dropdown">
                <a
                  class="nav-link dropdown-toggle"
                  href="#"
                  id="userActions"
                  data-toggle="dropdown"
                  aria-haspopup="true"
                  aria-expanded="false"
                  >{{current_user.first_name | capitalize}}</a
                >
                <div class="dropdown-menu" aria-labelledby="userActions">
                  <a class="dropdown-item" href="{{ url_for('auth.logout') }}"
                    >Logout</a
                  >
                </div>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.signin') }}"
                  >Sign in</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{{ url_for('auth.signup') }}"
                  >Sign Up</a
                >
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <!-- Flash Messages -->
    <!-- {% with messages = get_flashed_messages(with_categories=true) %} {% if
      messages %} {% for category, message in messages %}
      <div class="small alert alert-{{ category }} alert-dismisible">
        <button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">Close</span>
        </button>
        {{ message }}
      </div>
      {% endfor %} {% endif %} {% endwith %} -->
    <!-- Main Content -->
    {% block content %}{% endblock %}
    <!-- Footer-->
    <footer>
      <div class="container-fluid bg-white py-3">
        </div>
        <!-- Copyrights -->
    <div class="text-center">
          <p class="text-muted mb-0 py-2">
            &copy; {{ config.APP_NAME }} 2021
          </p>
        </div>
      </div>
    </footer>
    <!-- scripts -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
    <script
      src="{{ url_for('static', filename='js/main.js') }}"
      type="text/javascript"
    ></script>
    {% block scripts %}{% endblock %}
  </body>
</html>

app/templates/error.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron my-4">
  <div class="text-center">
    <h1>{{ '%s - %s' % (error.code, error.name) }}</h1>
    <p>{{ error.description }}.</p>
  </div>
</div>
{% endblock %}

app/templates/index.html
{% extends "base.html" %} {% block content %}
<div class="container">
  <p></p>
  <div class="row">
    {% for dashboard in dashboards%}

    <div class="col-sm-12 col-lg-4">
      <div class="card" style="width: 22rem">
        <div class="card-body" style="height: 17rem">
          <h5 class="card-title">{{ dashboard.title }}</h5>
          <p class="card-text">{{ dashboard.description | truncate(250) }}</p>
          <a href="{{ dashboard.url }}" class="btn btn-secondary"
            >See Dashboard</a
          >
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}